### ISSUE TITLE
[Bug]: Code 1101, MEMBER_NOT_EXIST

### ISSUE THREAD

**Issue by OingoFan55** [jjjonesjr33/petlibro#48]
### What happened ?

When setting up the integration (via login creds), receive Unexpected Error message.  Upon setting up debug, find Code 1101, MEMBER_NOT_EXIST in the log file.  Verified member creds are correct.  Others in HA forum report same issue.

![Petlibro_member_not_exist](https://github.com/user-attachments/assets/9dc7bcf8-1e1a-4258-a4dd-de8f94d78fce)

### Relevant log output

```python
2024-12-22 07:51:49.279 WARNING (MainThread) [custom_components.petlibro.api] No token available for request. Attempting to log in...
2024-12-22 07:51:49.874 ERROR (MainThread) [custom_components.petlibro.api] Login failed: Code: 1101, Message: MEMBER_NOT_EXIST
2024-12-22 07:51:49.874 ERROR (MainThread) [custom_components.petlibro.config_flow] Unexpected exception during validation: Login attempt failed: Code: 1101, Message: MEMBER_NOT_EXIST
Traceback (most recent call last):
  File "/config/custom_components/petlibro/api.py", line 207, in login
    data = await self.session.request("POST", "/member/auth/login", json={
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<10 lines>...
    })
    ^^
  File "/config/custom_components/petlibro/api.py", line 107, in request
    raise PetLibroAPIError(f"Code: {data.get('code')}, Message: {data.get('msg')}")
custom_components.petlibro.exceptions.PetLibroAPIError: Code: 1101, Message: MEMBER_NOT_EXIST
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/config/custom_components/petlibro/config_flow.py", line 125, in _validate_input
    self.token = await api.login(self.email, self.password)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/petlibro/api.py", line 230, in login
    raise PetLibroAPIError(f"Login attempt failed: {e}")
custom_components.petlibro.exceptions.PetLibroAPIError: Login attempt failed: Code: 1101, Message: MEMBER_NOT_EXIST
```

**Comment by jjjonesjr33** [comment]
@OingoFan55 we are seeing similar users having issues - I've pinned https://github.com/jjjonesjr33/petlibro/issues/38 as a global spot to talk about what's going on with accounts. 

From what I’ve noticed, creating an account on the app is completely separate from their web domains. It looks like no matter which region you pick, as long as you create the account through the app, it lets you access the API.

Did you setup your user account via their website or the app?

**Comment by OingoFan55** [comment]
I setup on the app and found the problem.  I setup the account with a different email account and even though I changed the email address weeks ago, it was still using my old email address for the login.  This is a problem with Petlibro and not your code.  Please close the bug report.  Thx!!!

**Comment by jjjonesjr33** [comment]
Shall do, thanks for letting me know @OingoFan55
